# Numpy (Numerical python)
AI Model understands only numbers
like
    Text -> Numerical date (tokenization)

In [1]:
!pip install numpy

   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.3 MB 8.4 MB/s eta 0:00:02
   ----------- ---------------------------- 3.4/12.3 MB 11.5 MB/s eta 0:00:01
   ---------------- ----------------------- 5.0/12.3 MB 10.4 MB/s eta 0:00:01
   -------------------- ------------------- 6.3/12.3 MB 8.8 MB/s eta 0:00:01
   ----------------------- ---------------- 7.3/12.3 MB 8.2 MB/s eta 0:00:01
   ---------------------------- ----------- 8.7/12.3 MB 7.6 MB/s eta 0:00:01
   ------------------------------- -------- 9.7/12.3 MB 7.4 MB/s eta 0:00:01
   ----------------------------------- ---- 11.0/12.3 MB 7.1 MB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 7.0 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 6.7 MB/s eta 0:00:00



[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import numpy as np

arr1 = np.array([20,56,34,89,6,34]) # 1D array

print(arr1)

arr2 = np.array([
                [2,34,56,21,4],
                [2,34,56,21,4],
                [2,34,56,21,4]
                ]) # 2D array

print(arr2)

arr3 = np.zeros((3,4)) # empty array, 3 row and 4 columns with default value as 0
print(arr3)

[20 56 34 89  6 34]
[[ 2 34 56 21  4]
 [ 2 34 56 21  4]
 [ 2 34 56 21  4]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
rng = np.arange(0, 20, 2) # build a array based on interval, in this - start with 0, till 20 (excluded) with interval of 2
print(rng)

[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
linsp = np.linspace(0, 1, 6) # build a array based on 2 number and split into n equal pieces
print(linsp)

[0.  0.2 0.4 0.6 0.8 1. ]


In [14]:
# array property
print('shape',arr2.shape)
print('dimension',arr2.ndim)
print('size',arr2.size)
print('data type',arr2.dtype)
print('memory',arr2.itemsize, 'bytes')

shape (3, 5)
dimension 2
size 15
data type int64
memory 8 bytes


In [18]:
# Indexing / slicing

arr4 = np.array([[12, 33, 55, 66],
                [13, 34, 53, 26],
                [11, 53, 25, 16]])

print(arr4)
# Index
'''
      0  1  2
   0 [1, 2, 3]
   1 [5, 6, 7]
   2 [4, 8, 9]
'''
print(arr4[0,1])
print(arr4[-1,-1])

[[12 33 55 66]
 [13 34 53 26]
 [11 53 25 16]]
33
16


In [ ]:
# Slicing
print('first 2 row', arr4[:2, :])

# slicing syntex
'''
     Row         Column
arr4[start:stop, start:stop]
if start value not specified then it takes from starting
if stop value not specified then it takes till the end
'''

# print('first 2 row', arr4[:2, :])
'''
print till 2nd row and all columns
'''

print('first 2 column', arr4[:, :2])
'''
print till all rows and till 2 column
'''


first 2 row [[12 33 55 66]
 [13 34 53 26]]
first 2 column [[12 33]
 [13 34]
 [11 53]]


In [23]:
# math operations
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(a+b)
print(a-b)

[ 6  8 10 12]
[-4 -4 -4 -4]


In [26]:
#scalar operation
print(a + 50)

#Universal functions
# square root 
print(np.sqrt(a))

# convert negative values to positive in array
c = [-2, 34, 54, -67]
print(np.abs(c))

[51 52 53 54]
[1.         1.41421356 1.73205081 2.        ]
[ 2 34 54 67]


In [ ]:
# Statistical operation

student_score = np.array([[]])

'''
minimum - np.min(array)
maximun - np.max(array)
average - np.mean(array)
median  - np.median(array)
std     - np.std(array).round(<int>)

calculate mean for row or column
np.mean(array, axis=0) # 0 is row, 1 is column

precentile - np.percentile(array, 25) # what is percentile, it's different from percentage, what is 25

Check on Boolean masking
'''

In [30]:
# Boolean masking
temps = np.array([20, 30, 40, 50, 60])

hot_city = temps > 35

print(hot_city)
print(temps[hot_city])

cold_city = temps < 25
print(cold_city)
print(temps[cold_city])

[False False  True  True  True]
[40 50 60]
[ True False False False False]
[20]
